version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db_app
    environment:
      MYSQL_ROOT_PASSWORD: admin  
      MYSQL_DATABASE: tfgapp_db   
      MYSQL_USER: root           
      MYSQL_PASSWORD: admin       
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend_app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tfgapp_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
