export const TEXT_CONSTANTS = {
  en: {
    language: "Language",
    spanish: "Spanish",
    english: "English",
    settings: "Settings",
    appearance: "Appearance",
    appearanceDesc: "Customize how the app looks.",
    darkTheme: "Dark theme",
    darkThemeHint: "Enable or disable dark mode.",
    translucentTheme: "Translucent theme",
    translucentThemeHint: "Makes the window transparent so the desktop can be seen.",
    profile: "Profile",
    profileDesc: "Update your profile photo.",
    uploadPhoto: "Upload photo",
    removePhoto: "Remove photo",
    account: "Account",
    accountDesc: "Update your username.",
    username: "Username",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm new password",
    saveUsername: "Save username",
    security: "Security",
    securityDesc: "Change your login password.",
    changePassword: "Change password",
    calendarPrevious: "Previous",
    calendarToday: "Today",
    calendarNext: "Next",
    calendarDay: "Day",
    calendarWeek: "Week",
    calendarMonth: "Month",
    goalEditTitle: "Edit Goal",
    goalNewTitle: "New Goal",
    habitEditTitle: "Edit Habit",
    habitNewTitle: "New Habit",
    habitCreateButton: "Create Habit",
    habitTitlePlaceholder: "Ex: Read 30 minutes",
    habitDescriptionPlaceholder: "Describe your habit...",
    commonTitle: "Title",
    commonDescription: "Description",
    commonActive: "Active",
    commonCancel: "Cancel",
    commonSaving: "Saving...",
    commonUpdate: "Update",
    calendarSearchTime: "Search time...",
    calendarDeleteConfirm: "Are you sure you want to delete this event?",
    calendarStart: "Start",
    calendarEnd: "End",
    calendarAllDay: "All day",
    calendarAddTitle: "Add title",
    calendarAddLocation: "Add location",
    calendarAddDescription: "Add description",
    commonUser: "User",
    commonMultipleUsers: "Multiple users",
    commonAllOrganization: "All (organization)",
    commonSelectUser: "Select a user",
    commonAssignment: "Assignment",
    commonPriority: "Priority",
    priorityHigh: "High",
    priorityMedium: "Medium",
    priorityLow: "Low",
    commonStatus: "Status",
    commonSaveChanges: "Save changes",
    goalCreateButton: "Create Goal",
    goalTitlePlaceholder: "Ex: Finish project",
    goalDescriptionPlaceholder: "Describe your goal...",
    calendarSelectManagedUser: "Select managed user",
    calendarReminders: "Reminders",
    calendarCustomMinutes: "Custom minutes",
    calendarNoReminders: "No reminders.",
    calendarMoreOptions: "More options",
    commonDelete: "Delete",
    commonSave: "Save",
    commonCreate: "Create",
    commonAdd: "Add",
    goalStatusNotStarted: "Not started",
    goalStatusInProgress: "In progress",
    goalStatusDone: "Done",
    goalCurrentValue: "Current value",
    goalCurrentValuePlaceholder: "0",
    goalTargetValue: "Target value",
    goalTargetValuePlaceholder: "100",
    goalProgressNote: "Progress note",
    goalProgressNotePlaceholder: "Optional: note for progress history",
    goalNumericObjective: "Numeric objective",
    loginTitle: "Log-in",
    loginPassword: "Password",
    loginConnectionError: "Connection error, try again.",
    registerTitle: "Register",
    registerUsernameRequired: "Username is required.",
    registerUsernameNoSpaces: "Username cannot contain spaces.",
    registerPasswordRequired: "Password is required.",
    registerPasswordHelp: "Password must have at least 10 characters, letters, one number and one symbol.",
    homeGoalsStats: "Goals stats",
    homeTotal: "Total",
    homeActive: "Active",
    homeInProgress: "In progress",
    homeDone: "Done",
    homeGlobalProgress: "Global progress of selected user",
    homeNoManagedUsers: "You don't have managed users yet.",
    homeNoOrganization: "No organization",
    homeLoading: "Loading...",
    objectivesLoadError: "Could not load objectives screen.",
    objectivesContextError: "Could not load context.",
    objectivesGoalTitleRequired: "Goal title is required.",
    objectivesSelectUserRequired: "You must select at least one managed user.",
    objectivesProgressUpdateNote: "Progress update from frontend.",
    objectivesGoalSaveError: "Could not save goal.",
    menuTitle: "Menu",
    menuHome: "Home",
    menuCalendar: "Calendar",
    menuObjectives: "Objectives",
    menuUsers: "Users",
    menuBlock: "Block",
    myAccount: "My account",
    signOut: "Sign Out",
    userDefault: "User",
    logoutFailed: "Log out failed.",
    blockFocusMode: "Focus mode",
    blockOff: "Off",
    blockTimeTracker: "Time Tracker",
    blockBubbleContent: "This window provides tools for healthier computer use, with regular breaks and focus support.",
    blockRestingLower: "resting",
    blockNextBreakLower: "next break",
    blockResting: "Resting",
    blockFocusLockedTitle: "Focus mode locked by active Focus event",
    blockToggleFocusTitle: "Enable/disable focus mode",
    blockWork: "Work",
    blockBreak: "Break",
    blockOnFinish: "On finish",
    blockNotification: "Notification",
    blockScreen: "Block screen",
    blockManage: "Manage",
    blockSearchApp: "Search app to block...",
    blockLoadingApps: "Loading apps...",
    blockInstalled: "installed",
    blockAddManual: "Add manually",
    blockManual: "manual",
    blockNoAppsFound: "No installed apps found",
    blockTypeToSearch: "Type to search installed apps",
    blockRemoveFromList: "Remove from list",
    blockResetList: "Reset full list",
    blockNoBlockedApps: "No blocked apps",
    blockAddFromTab: "Add apps from the Add tab",
    commonCreating: "Creating...",
    adminOrgSetupTitle: "Set up your organization",
    adminOrgSetupSubtitle:
      "First access detected: create your organization before using admin view.",
    adminOrgCreateTitle: "Create organization",
    adminOrgName: "Organization name",
    adminOrgPlaceholder: "Ex: Productive Academy",
    adminOrgCreateBtn: "Create organization",
    adminOrgNameRequired: "Organization name is required.",
    adminOrgCreateError: "Could not create organization.",
    commonReload: "Reload",
    adminUsersTitle: "User management",
    adminUsersSubtitle: "Create and remove managed users in your organization.",
    adminCreateManaged: "Create managed user",
    adminManagedUsers: "Managed users",
    adminLoadingUsers: "Loading users...",
    adminNoUsers: "No managed users.",
    adminOrganization: "Organization",
    adminDeleteBtn: "Delete",
    adminUsersLoadError: "Could not load users.",
    adminUsersRequired: "Username and password are required.",
    adminUser: "User",
    adminCreated: "created successfully.",
    adminCreateError: "Could not create user.",
    adminConfirmDeletePrefix: "Are you sure you want to delete",
    adminDeleted: "deleted successfully.",
    adminDeleteError: "Could not delete user.",
    commonBy: "By",
    commonEdit: "Edit",
    commonProgress: "Progress",
    commonActions: "Actions",
    commonToday: "Today",
    goalsAssigned: "Assigned",
    goalsTitle: "Goals",
    goalsSubtitle: "Long-term goals with progress tracking",
    goalsNew: "New Goal",
    goalsEmpty: "No active goals. Start by adding one.",
    goalsHideCompleted: "Hide completed",
    goalsShowCompleted: "Show completed",
    habitsTitle: "Habits",
    habitsSubtitle: "Daily tracking with streaks and stats",
    habitsNew: "New Habit",
    habitsStreak: "Streak",
    habitsBest: "Best",
    habitsEmpty: "No habits created. Start by adding one.",
    dashboardGoalsProgress: "Goals progress",
    dashboardDoneToday: "Completed today",
    dashboardWeeklyRate: "Weekly completion",
    dashboardBestStreak: "Best streak",
    dashboardGoalsSummary: "Goals summary",
    dashboardGoalsAverageProgress: "Average progress of active goals",
    dashboardWeeklyActivity: "Weekly activity",
    placeholders: {
      newUsername: "Type your new username",
      currentPassword: "Type your current password",
      newPassword: "Type your new password",
      confirmPassword: "Repeat your new password",
    },
    messages: {
      profileLoadError: "Unable to load profile.",
      profileUpdateSuccess: "Profile image updated successfully.",
      profileUpdateError: "Unable to update profile image.",
      profileDeleteSuccess: "Profile image removed successfully.",
      profileDeleteError: "Unable to remove profile image.",
      usernameMissingData: "You must type a new username and your current password.",
      usernameUpdateSuccess: "Username updated successfully.",
      usernameUpdateError: "Unable to update username.",
      passwordMissingData: "You must complete all fields.",
      passwordNoMatch: "Passwords do not match.",
      passwordUpdateSuccess: "Password updated successfully.",
      passwordUpdateError: "Unable to update password.",
    },
  },
  es: {
    language: "Idioma",
    spanish: "Español",
    english: "Inglés",
    settings: "Settings",
    appearance: "Apariencia",
    appearanceDesc: "Personaliza cómo se ve la aplicación.",
    darkTheme: "Tema oscuro",
    darkThemeHint: "Activa o desactiva el modo oscuro.",
    translucentTheme: "Tema translúcido",
    translucentThemeHint: "Hace la ventana transparente para que se vea el escritorio.",
    profile: "Perfil",
    profileDesc: "Actualiza tu foto de perfil.",
    uploadPhoto: "Subir foto",
    removePhoto: "Quitar foto",
    account: "Cuenta",
    accountDesc: "Actualiza tu nombre de usuario.",
    username: "Nombre de usuario",
    currentPassword: "Contraseña actual",
    newPassword: "Nueva contraseña",
    confirmPassword: "Confirmar nueva contraseña",
    saveUsername: "Guardar username",
    security: "Seguridad",
    securityDesc: "Cambia tu contraseña de acceso.",
    changePassword: "Cambiar contraseña",
    calendarPrevious: "Anterior",
    calendarToday: "Hoy",
    calendarNext: "Siguiente",
    calendarDay: "Día",
    calendarWeek: "Semana",
    calendarMonth: "Mes",
    goalEditTitle: "Editar Goal",
    goalNewTitle: "Nuevo Goal",
    habitEditTitle: "Editar Hábito",
    habitNewTitle: "Nuevo Hábito",
    habitCreateButton: "Crear Hábito",
    habitTitlePlaceholder: "Ej. Leer 30 minutos",
    habitDescriptionPlaceholder: "Describe tu hábito...",
    commonTitle: "Título",
    commonDescription: "Descripción",
    commonActive: "Activo",
    commonCancel: "Cancelar",
    commonSaving: "Guardando...",
    commonUpdate: "Actualizar",
    calendarSearchTime: "Buscar hora...",
    calendarDeleteConfirm: "¿Estás seguro de que deseas eliminar este evento?",
    calendarStart: "Inicio",
    calendarEnd: "Fin",
    calendarAllDay: "Todo el día",
    calendarAddTitle: "Añadir título",
    calendarAddLocation: "Añadir ubicación",
    calendarAddDescription: "Añadir descripción",
    commonUser: "Usuario",
    commonMultipleUsers: "Varios usuarios",
    commonAllOrganization: "Todos (organización)",
    commonSelectUser: "Selecciona un usuario",
    commonAssignment: "Asignación",
    commonPriority: "Prioridad",
    priorityHigh: "Alta",
    priorityMedium: "Media",
    priorityLow: "Baja",
    commonStatus: "Estado",
    commonSaveChanges: "Guardar cambios",
    goalCreateButton: "Crear Goal",
    goalTitlePlaceholder: "Ej. Terminar proyecto",
    goalDescriptionPlaceholder: "Describe tu goal...",
    calendarSelectManagedUser: "Selecciona usuario subordinado",
    calendarReminders: "Recordatorios",
    calendarCustomMinutes: "Minutos personalizados",
    calendarNoReminders: "Sin alertas.",
    calendarMoreOptions: "Más opciones",
    commonDelete: "Eliminar",
    commonSave: "Guardar",
    commonCreate: "Crear",
    commonAdd: "Añadir",
    goalStatusNotStarted: "Sin empezar",
    goalStatusInProgress: "En progreso",
    goalStatusDone: "Completado",
    goalCurrentValue: "Valor actual",
    goalCurrentValuePlaceholder: "0",
    goalTargetValue: "Valor objetivo",
    goalTargetValuePlaceholder: "100",
    goalProgressNote: "Nota del progreso",
    goalProgressNotePlaceholder: "Opcional: nota para el historial de progreso",
    goalNumericObjective: "Objetivo numérico",
    loginTitle: "Log-in",
    loginPassword: "Contraseña",
    loginConnectionError: "Error de conexión, inténtalo de nuevo.",
    registerTitle: "Register",
    registerUsernameRequired: "El username es obligatorio.",
    registerUsernameNoSpaces: "El username no puede contener espacios.",
    registerPasswordRequired: "La contraseña es obligatoria.",
    registerPasswordHelp: "La contraseña debe tener al menos 10 caracteres, incluir letras, un número y un símbolo",
    homeGoalsStats: "Estadísticas de goals",
    homeTotal: "Total",
    homeActive: "Activos",
    homeInProgress: "En progreso",
    homeDone: "Completados",
    homeGlobalProgress: "Avance global del usuario seleccionado",
    homeNoManagedUsers: "No tienes usuarios subordinados todavía.",
    homeNoOrganization: "Sin organización",
    homeLoading: "Cargando...",
    objectivesLoadError: "No se pudo cargar la pantalla de objetivos.",
    objectivesContextError: "No se pudo cargar el contexto.",
    objectivesGoalTitleRequired: "El titulo del goal es obligatorio.",
    objectivesSelectUserRequired: "Debes seleccionar al menos un usuario subordinado.",
    objectivesProgressUpdateNote: "Actualizacion de progreso desde frontend.",
    objectivesGoalSaveError: "No se pudo guardar el goal.",
    menuTitle: "Menu",
    menuHome: "Home",
    menuCalendar: "Calendar",
    menuObjectives: "Objectives",
    menuUsers: "Users",
    menuBlock: "Block",
    myAccount: "Mi cuenta",
    signOut: "Sign Out",
    userDefault: "User",
    logoutFailed: "Log out failed.",
    blockFocusMode: "Focus mode",
    blockOff: "Off",
    blockTimeTracker: "Time Tracker",
    blockBubbleContent: "Esta ventana está dedicada a ofrecer herramientas para gestionar un uso más saludable del ordenador, fomentando descansos regulares y ayudándote a mantener el enfoque.",
    blockRestingLower: "descansando",
    blockNextBreakLower: "próximo descanso",
    blockResting: "Descansando",
    blockFocusLockedTitle: "Focus mode bloqueado por evento Focus activo",
    blockToggleFocusTitle: "Activar/desactivar focus mode",
    blockWork: "Trabajo",
    blockBreak: "Descanso",
    blockOnFinish: "Al terminar",
    blockNotification: "Notificación",
    blockScreen: "Block screen",
    blockManage: "Gestionar",
    blockSearchApp: "Buscar aplicación para bloquear...",
    blockLoadingApps: "Cargando aplicaciones...",
    blockInstalled: "instalada",
    blockAddManual: "Añadir manualmente",
    blockManual: "manual",
    blockNoAppsFound: "No se encontraron aplicaciones instaladas",
    blockTypeToSearch: "Escribe para buscar entre las aplicaciones instaladas",
    blockRemoveFromList: "Eliminar de la lista",
    blockResetList: "Resetear lista completa",
    blockNoBlockedApps: "No hay aplicaciones bloqueadas",
    blockAddFromTab: "Añade aplicaciones desde la pestaña Añadir",
    commonCreating: "Creando...",
    adminOrgSetupTitle: "Configura tu organización",
    adminOrgSetupSubtitle:
      "Primer acceso detectado: antes de usar la vista admin, debes crear la organización que vas a gestionar.",
    adminOrgCreateTitle: "Alta de organización",
    adminOrgName: "Nombre de la organización",
    adminOrgPlaceholder: "Ej: Academia Productiva",
    adminOrgCreateBtn: "Crear organización",
    adminOrgNameRequired: "Debes indicar un nombre para la organización.",
    adminOrgCreateError: "No se pudo crear la organización.",
    commonReload: "Recargar",
    adminUsersTitle: "Gestión de usuarios",
    adminUsersSubtitle: "Alta y baja de usuarios subordinados de tu organización.",
    adminCreateManaged: "Crear usuario subordinado",
    adminManagedUsers: "Usuarios subordinados",
    adminLoadingUsers: "Cargando usuarios...",
    adminNoUsers: "No hay usuarios subordinados.",
    adminOrganization: "Organización",
    adminDeleteBtn: "Dar de baja",
    adminUsersLoadError: "No se pudieron cargar los usuarios.",
    adminUsersRequired: "Debes indicar username y contraseña.",
    adminUser: "Usuario",
    adminCreated: "creado correctamente.",
    adminCreateError: "No se pudo crear el usuario.",
    adminConfirmDeletePrefix: "¿Seguro que quieres dar de baja a",
    adminDeleted: "eliminado correctamente.",
    adminDeleteError: "No se pudo eliminar el usuario.",
    commonBy: "Por",
    commonEdit: "Editar",
    commonProgress: "Progreso",
    commonActions: "Acciones",
    commonToday: "Hoy",
    goalsAssigned: "Asignado",
    goalsTitle: "Goals",
    goalsSubtitle: "Metas a largo plazo con seguimiento de progreso",
    goalsNew: "Nuevo Goal",
    goalsEmpty: "No hay goals activos. Comienza añadiendo uno.",
    goalsHideCompleted: "Ocultar completados",
    goalsShowCompleted: "Mostrar completados",
    habitsTitle: "Hábitos",
    habitsSubtitle: "Seguimiento diario con rachas y estadísticas",
    habitsNew: "Nuevo Hábito",
    habitsStreak: "Racha",
    habitsBest: "Mejor",
    habitsEmpty: "No hay hábitos creados. Comienza añadiendo uno.",
    dashboardGoalsProgress: "Avance goals",
    dashboardDoneToday: "Completados hoy",
    dashboardWeeklyRate: "Cumplimiento semanal",
    dashboardBestStreak: "Mejor racha",
    dashboardGoalsSummary: "Resumen de Goals",
    dashboardGoalsAverageProgress: "Progreso medio de los goals activos",
    dashboardWeeklyActivity: "Actividad Semanal",
    placeholders: {
      newUsername: "Introduce tu nuevo nombre de usuario",
      currentPassword: "Introduce tu contraseña actual",
      newPassword: "Introduce tu nueva contraseña",
      confirmPassword: "Repite tu nueva contraseña",
    },
    messages: {
      profileLoadError: "No se pudo cargar el perfil.",
      profileUpdateSuccess: "Imagen de perfil actualizada correctamente.",
      profileUpdateError: "No se pudo actualizar la foto de perfil.",
      profileDeleteSuccess: "Imagen eliminada correctamente.",
      profileDeleteError: "No se pudo eliminar la foto.",
      usernameMissingData: "Debes introducir el nuevo username y tu contraseña actual.",
      usernameUpdateSuccess: "Username actualizado correctamente.",
      usernameUpdateError: "No se pudo actualizar el username.",
      passwordMissingData: "Debes rellenar todos los campos.",
      passwordNoMatch: "Las contraseñas no coinciden.",
      passwordUpdateSuccess: "Contraseña actualizada correctamente.",
      passwordUpdateError: "No se pudo actualizar la contraseña.",
    },
  },
};
