export const TEXT_CONSTANTS = {
  en: {
    language: "Language",
    spanish: "Spanish",
    english: "English",
    settings: "Settings",
    appearance: "Appearance",
    appearanceDesc: "Customize how the app looks.",
    darkTheme: "Dark theme",
    darkThemeHint: "Enable or disable dark mode.",
    translucentTheme: "Translucent theme",
    translucentThemeHint: "Makes the window transparent so the desktop can be seen.",
    profile: "Profile",
    profileDesc: "Update your profile photo.",
    uploadPhoto: "Upload photo",
    removePhoto: "Remove photo",
    account: "Account",
    accountDesc: "Update your username.",
    username: "Username",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm new password",
    saveUsername: "Save username",
    security: "Security",
    securityDesc: "Change your login password.",
    changePassword: "Change password",
    calendarPrevious: "Previous",
    calendarToday: "Today",
    calendarNext: "Next",
    calendarDay: "Day",
    calendarWeek: "Week",
    calendarMonth: "Month",
    goalEditTitle: "Edit Goal",
    goalNewTitle: "New Goal",
    habitEditTitle: "Edit Habit",
    habitNewTitle: "New Habit",
    habitCreateButton: "Create Habit",
    habitTitlePlaceholder: "Ex: Read 30 minutes",
    habitDescriptionPlaceholder: "Describe your habit...",
    commonTitle: "Title",
    commonDescription: "Description",
    commonActive: "Active",
    commonCancel: "Cancel",
    commonSaving: "Saving...",
    commonUpdate: "Update",
    placeholders: {
      newUsername: "Type your new username",
      currentPassword: "Type your current password",
      newPassword: "Type your new password",
      confirmPassword: "Repeat your new password",
    },
    messages: {
      profileLoadError: "Unable to load profile.",
      profileUpdateSuccess: "Profile image updated successfully.",
      profileUpdateError: "Unable to update profile image.",
      profileDeleteSuccess: "Profile image removed successfully.",
      profileDeleteError: "Unable to remove profile image.",
      usernameMissingData: "You must type a new username and your current password.",
      usernameUpdateSuccess: "Username updated successfully.",
      usernameUpdateError: "Unable to update username.",
      passwordMissingData: "You must complete all fields.",
      passwordNoMatch: "Passwords do not match.",
      passwordUpdateSuccess: "Password updated successfully.",
      passwordUpdateError: "Unable to update password.",
    },
  },
  es: {
    language: "Idioma",
    spanish: "Español",
    english: "Inglés",
    settings: "Settings",
    appearance: "Apariencia",
    appearanceDesc: "Personaliza cómo se ve la aplicación.",
    darkTheme: "Tema oscuro",
    darkThemeHint: "Activa o desactiva el modo oscuro.",
    translucentTheme: "Tema translúcido",
    translucentThemeHint: "Hace la ventana transparente para que se vea el escritorio.",
    profile: "Perfil",
    profileDesc: "Actualiza tu foto de perfil.",
    uploadPhoto: "Subir foto",
    removePhoto: "Quitar foto",
    account: "Cuenta",
    accountDesc: "Actualiza tu nombre de usuario.",
    username: "Nombre de usuario",
    currentPassword: "Contraseña actual",
    newPassword: "Nueva contraseña",
    confirmPassword: "Confirmar nueva contraseña",
    saveUsername: "Guardar username",
    security: "Seguridad",
    securityDesc: "Cambia tu contraseña de acceso.",
    changePassword: "Cambiar contraseña",
    calendarPrevious: "Anterior",
    calendarToday: "Hoy",
    calendarNext: "Siguiente",
    calendarDay: "Día",
    calendarWeek: "Semana",
    calendarMonth: "Mes",
    goalEditTitle: "Editar Goal",
    goalNewTitle: "Nuevo Goal",
    habitEditTitle: "Editar Hábito",
    habitNewTitle: "Nuevo Hábito",
    habitCreateButton: "Crear Hábito",
    habitTitlePlaceholder: "Ej. Leer 30 minutos",
    habitDescriptionPlaceholder: "Describe tu hábito...",
    commonTitle: "Título",
    commonDescription: "Descripción",
    commonActive: "Activo",
    commonCancel: "Cancelar",
    commonSaving: "Guardando...",
    commonUpdate: "Actualizar",
    placeholders: {
      newUsername: "Introduce tu nuevo nombre de usuario",
      currentPassword: "Introduce tu contraseña actual",
      newPassword: "Introduce tu nueva contraseña",
      confirmPassword: "Repite tu nueva contraseña",
    },
    messages: {
      profileLoadError: "No se pudo cargar el perfil.",
      profileUpdateSuccess: "Imagen de perfil actualizada correctamente.",
      profileUpdateError: "No se pudo actualizar la foto de perfil.",
      profileDeleteSuccess: "Imagen eliminada correctamente.",
      profileDeleteError: "No se pudo eliminar la foto.",
      usernameMissingData: "Debes introducir el nuevo username y tu contraseña actual.",
      usernameUpdateSuccess: "Username actualizado correctamente.",
      usernameUpdateError: "No se pudo actualizar el username.",
      passwordMissingData: "Debes rellenar todos los campos.",
      passwordNoMatch: "Las contraseñas no coinciden.",
      passwordUpdateSuccess: "Contraseña actualizada correctamente.",
      passwordUpdateError: "No se pudo actualizar la contraseña.",
    },
  },
};
